### PR TITLE
Small fix. Comic Vine requires a user agent now

### PR DESCRIPTION
**Pull request by namanix**

### CODE REVIEW

**Comment by Clearmist** [comment]
Thank you for making this fix, namanix.

**Comment by Remrap** [comment]
Thank you!  How do we apply this change?

**Comment by cbanack** [comment]
Easiest thing to do is wait for a day or two until I get chance to rebuild Comic Vine Scraper with and post a [new release](https://github.com/cbanack/comic-vine-scraper/releases).   This fix will be included in that release.

**Comment by Remrap** [comment]
You rock!  Thank you again for the update.

**Comment by cbanack** [comment]
This pull request fixes issue 429.

**Pull request merged**
